@API_HostAddress = http://localhost:5106

POST  {{API_HostAddress}}/auth/register
Content-Type: application/json

{
    "FirstName":"Alexis",
    "LastName":"Torres",
    "Email":"Dat.Torres@gmail.com",
    "Password":"dantorres123."
}
